### ISSUE TITLE
Fallback versions not supported

### ISSUE THREAD

**Issue by reitzig** [asciidoctor/asciidoctor-intellij-plugin#1140]
## Observed vs. expected behavior

The plugin does not seem to support [Fallback Versions](https://docs.antora.org/antora/latest/playbook/content-source-version/) (an antora 3.x feature, far as I can tell).

FWIW: The plugin documentation doesn't indicate exclusive support of antora 2.x, so I'm creating this as a bug. 
Apologies if you consider it a feature request instead.

## Steps to reproduce

Setup according to the docs (green builds on my end, too):

```yaml
# antora.yml
name: my-module
# version: main # NB: Unversioned, cf. including playbook

title: My Module
start_page: ROOT:index.adoc
nav:
  - modules/ROOT/nav.adoc
```

```yaml
# antora-playbook.yml
site:
  title: My Website
  start_page: my-module:ROOT:index.adoc
content:
  sources:
  - url: https://some.server/my-module.git
    branches: main
    version: ~  # aka unversioned
    start_path: docs

# /snip
```

**Expected:** Green files, syntax completion.

**Actual:**

 - `content.sources[].version` in `antora-playbook.yml` not supported:  
   ![image](https://user-images.githubusercontent.com/4246780/186129058-f03700da-1517-4046-b610-71859e2cf110.png)
- `version` in `antora.yml` required:  
  ![image](https://user-images.githubusercontent.com/4246780/186129297-e169d376-a613-4480-b1e6-5fa117481df2.png)

FWIW, [refname projection](https://docs.antora.org/antora/latest/playbook/content-source-version/#refname-projection-as-version) probably requires additional consideration.

## Environment

Plugin Version: 0.37.43

PyCharm 2022.2.1 (Professional Edition)
Build #PY-222.3739.56, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-43-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2500M
Cores: 8
Registry:
    debugger.click.disable.breakpoints=true

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    org.jetbrains.plugins.go-template (222.3739.24)
    name.kropp.intellij.makefile (222.3739.24)
    com.intellij.plugins.macoskeymap (222.3739.24)
    com.intellij.ideolog (203.0.30.0)
    com.github.mikesafonov.jenkins-linter-idea-plugin (0.6.0)
    com.dmarcotte.handlebars (222.3739.24)
    Key Promoter X (2022.2)
    org.sonarlint.idea (7.0.0.52289)
    org.asciidoctor.intellij.asciidoc (0.37.43)
    ir.msdehghan.plugins.ansible (0.92)
    ru.meanmail.plugin.requirements (2022.3-222-EAP-SNAPSHOT)
    net.ashald.envfile (3.2.2)
    com.intellij.kubernetes (222.3739.24)

Current Desktop: i3
