### ISSUE TITLE
callout lists are displayed like normal numbered lists, not like the callouts in the literal or listing block

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#149]
``` asciidoc
----
foo <1>
bar <2>
----

<1> foo
<2> bar
```

Does display like ![example1](https://cloud.githubusercontent.com/assets/325196/19840401/330d7eec-9ef5-11e6-97e7-e1f60f2f14ec.JPG) while it probably should display like ![example2](https://cloud.githubusercontent.com/assets/325196/19840408/69f33640-9ef5-11e6-9115-15ccbb586fb8.JPG)

**Comment by ahus1** [comment]
I see your point. You should raise this with the Asciidoctor project if it hasn't been raised already. 

On the other hand, when using when using Asciidoctor to render, you could use the font-icons options (only available in Asciidoctor). 

```
:icons: font
----
foo <1>
bar <2>
----

<1> foo
<2> bar
``` 

![image](https://cloud.githubusercontent.com/assets/3957921/20033193/c5a5c840-a39b-11e6-83df-9755edf4605d.png)

See http://asciidoctor.org/docs/user-manual/#callout-icons

**Comment by mojavelinux** [comment]
I like this idea. In CSS3, this is possible using a custom counter rule. It works today in Firefox. Just add the following to a docinfo file:

```css
@counter-style callout-number {
  system: extends decimal;
  prefix: "(";
  suffix: ") ";
}
.colist > ol {
  list-style-type: callout-number;
}
```

There are other ways to do it, but this is definitely the cleanest.
