### ISSUE TITLE
Autocomplete `xref` suggests version coord even if `true`

### ISSUE THREAD

**Issue by bartkl** [asciidoctor/asciidoctor-intellij-plugin#1708]
## Description

Hi,

I'm somewhat confused about the autocomplete behavior when cross-referencing pages in other component versions.

#### Playbook
Content sources section in my `antora-playbook-local.yml`:

```yaml
  sources:
    - url: .
      branches: HEAD
      start_path: ./root_component
    - url: ../doc-writing-guide/
      branches: HEAD
```

##### Root component version
The decriptor, i.e. contents of `antora.yml`:

```yaml
name: ROOT
title: Documentation
version: ~
nav:
- modules/ROOT/nav.adoc
```

##### _Writing Guide_ component version
The decriptor, i.e. contents of `antora.yml`:

```yaml
name: writing-guide
title: Writing Guide
version: true
prerelease: "-draft"
start_page: index.adoc
nav:
- modules/ROOT/nav.adoc
```

#### The problem
I'm editing the `ROOT/pages/index.adoc` file in my `ROOT` component, where I'm trying to cross-reference a page in my `writing-guide` component:

![image](https://github.com/user-attachments/assets/c65b6e1f-3b36-45b1-8c53-808d32f097f5)

As you can see from my typing, I don't want to refer to an explicit version here. Regardless, the autocomplete forces me to use that.

Is this expected behavior? Am I perhaps misunderstanding something?

Thanks for your help and this great plugin!
