### ISSUE TITLE
Support Antora 2.3 component attributes

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#385]
Antora 2.3 will support component scoped attributes like this. 

This should also be supported by the IntelliJ plugin. Values should be available when rendering and when editing (for auto-complete).

```
asciidoc:
  attributes:
    prodname: 'Debezium'
    assemblies: '../assemblies'
    modules: '../../modules'
    mysql-connector-plugin-download: 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.0.0.Final/debezium-connector-mysql-1.0.0.Final-plugin.tar.gz'
    mysql-version: '8.0'
    context: 'debezium'
```

See: https://gitlab.com/antora/antora/issues/251 and https://issues.redhat.com/browse/DBZ-1687
