### ISSUE TITLE
Using tilde `~` (null) in antora.yml should not produce a warning

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#581]
When using the following in `antora.yml`:

```yml
name: admin
title: Administration
version: 'master'
nav:
  - modules/ROOT/nav.adoc
asciidoc:
  attributes:
    toc: ~
```

I get the following warning message:

```
AsciiDoc attribute 'toc' is null in /path/to/antora.yml: Will be treated as unset. Use either false to explicitly unset, or set by providing for example an empty string ''
```

According to Dan:

> that is the correct syntax. valid values are `false`, `nil` (also written as `~`), or any of the enumerated values.
in a playbook, using false and nil are preferred over using !toc (since it's cleaner and easier to control keys)
see https://docs.antora.org/antora/2.3/playbook/asciidoc-attributes/#hard-unset

The message is a bit misleading and I think we should not warn when the value is explicitly null (`~`).
