### ISSUE TITLE
Schema validation: Property 'tags' is not allowed 

### ISSUE THREAD

**Issue by marcelstoer** [asciidoctor/asciidoctor-intellij-plugin#646]
## Observed vs. expected behavior

The plugin thinks `tags` be not an allowed key of the `sources` key in `antora-playbook.yml` - which it obviously is as per https://docs.antora.org/antora/2.3/playbook/configure-content-sources/#sources-key

I had a brief look at https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/resources/jsonSchemas/antoraPlaybookSchema.json but I don't see anything wrong with it at first glance.

## Steps to reproduce

```yaml
site:
  title: "demo"
content:
  edit_url: "{web_url}/edit/master/{path}"
  sources:
    - url: https://github.com/asciidoctor/asciidoctor-intellij-plugin
      start_path: doc
      tags: ['*.*.*']
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
```
<img width="450" alt="Screen Shot 2021-01-28 at 16 56 22" src="https://user-images.githubusercontent.com/624195/106164001-d2347880-6189-11eb-8e70-91d4b8e2ca92.png">

## Environment

Plugin Version: 0.32.12

IntelliJ Details: 
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Marcel Stör
Subscription is active until October 16, 2021.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.mac.hide.cursor.when.typing=false, debugger.watches.in.variables=false, editor.zero.latency.rendering=false
Non-Bundled Plugins: com.intellij.apacheConfig, com.jetbrains.plugins.ini4idea, org.zalando.intellij.swagger, com.tang, org.jetbrains.plugins.hocon, MavenRunHelper, com.dmarcotte.handlebars, org.jetbrains.kotlin, com.intellij.plugins.html.instantEditing, com.jetbrains.php, PlantUML integration, Pythonid, org.asciidoctor.intellij.asciidoc
