### ISSUE TITLE
Schema file in plugin needs updated.

### ISSUE THREAD

**Issue by scphantm** [asciidoctor/asciidoctor-intellij-plugin#757]
## Observed vs. expected behavior

the plugin doesn't recognize the validity of the `edit_url` tag.  

```
content:
  branches: master
  sources:
  - url: myazuresite
    edit_url: 'myazuresite?path={path}&version=GB{refname}&_a=contents'
    start_path: homepage
```

the jetbrains plugin says the edit_url is invalid, even tho it is.  The schema file in the plugin needs updated im guessing.

Plugin Version: ____

0.32.47
